#Target : Dependencies
#<TAB>commands

Build : calculatorMain.c calculator.out
	gcc calculatorMain.c calculator.c -o calculator.out

Run : calculator.out
	.\calculator.out

Clean :
	rm -rf *.o *.out *.i *.s		