#Target : Dependencies
#<TAB>commands

Build : calculatorMain.c calculator.out test_calculator.c unity.c
	gcc calculatorMain.c calculator.c test_calculator.c unity.c  -o calculator.out

Run : calculator.out
	.\calculator.out

Clean :
	rm -rf *.o *.out *.i *.s		